### PR TITLE
Add Calico support to openstack terraform

### PR DESCRIPTION
**Pull request by thequailman**
* Add compute ports with allowed addresses
* Add variable declarations

### CODE REVIEW

**Comment by thequailman** [comment]
Apologies for the terrible naming, "network_id" that is being passed to the compute module isn't really the network_id, it's the router_id 🤷‍♂️

**Comment by thequailman** [comment]
pod to pod on calico:
```1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 1a:b7:06:33:fa:6c brd ff:ff:ff:ff:ff:ff
    inet 10.2.161.130/32 scope global eth0
       valid_lft forever preferred_lft forever
/ # ping 10.2.12.67
PING 10.2.12.67 (10.2.12.67): 56 data bytes
64 bytes from 10.2.12.67: seq=0 ttl=62 time=1.961 ms
64 bytes from 10.2.12.67: seq=1 ttl=62 time=1.644 ms
64 bytes from 10.2.12.67: seq=2 ttl=62 time=1.414 ms
```
pod to service on calico:
```
/ # ping 10.3.250.243
PING 10.3.250.243 (10.3.250.243): 56 data bytes
64 bytes from 10.3.250.243: seq=0 ttl=64 time=0.209 ms
64 bytes from 10.3.250.243: seq=1 ttl=64 time=0.272 ms
64 bytes from 10.3.250.243: seq=2 ttl=64 time=0.083 ms
```
no flannel:
```
[15:33:45] mike@macbook ~/Code/kaasctl  kubectl get po -n kube-system
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-6f5f889c7c-fmtlb   1/1     Running   0          5m
calico-node-7ffdl                          1/1     Running   0          6m
calico-node-bsmjd                          1/1     Running   0          6m
calico-node-c2ccw                          1/1     Running   0          6m
calico-node-glbjb                          1/1     Running   0          6m
calico-node-msc2c                          1/1     Running   0          6m
calico-node-njtkv                          1/1     Running   0          6m
calico-node-xq944                          1/1     Running   0          6m
coredns-964b764bf-4r9qs                    1/1     Running   0          7m
coredns-964b764bf-577cj                    1/1     Running   0          4m
dns-autoscaler-67df466db7-r68ls            1/1     Running   0          7m
kube-proxy-5fjn2                           1/1     Running   0          5m```

**Review by waynr — CHANGES_REQUESTED** [review]
We can't merge this until we see CI on the rcbops/mk8s repo go green using it.

**Comment by waynr** [comment]
Closing this PR since we went with @stevemcquaid's PR instead.

**Pull request closed without merging**
